
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/"
      - "/Users/work/.local/bin/"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/"
      - "/opt/homebrew/opt/node@22/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/work/.dotnet/tools/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/work/.cargo/bin/"
      - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts/"
    searched_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/uname"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/uname"
      - "/Users/work/.local/bin/uname"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/uname"
      - "/opt/homebrew/opt/node@22/bin/uname"
      - "/opt/homebrew/opt/ruby/bin/uname"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/.cargo/bin"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 25.1.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/"
      - "/Users/work/.local/bin/"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/"
      - "/opt/homebrew/opt/node@22/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/work/.dotnet/tools/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/work/.cargo/bin/"
      - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts/"
    searched_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/gmake"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/gmake"
      - "/Users/work/.local/bin/gmake"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/gmake"
      - "/opt/homebrew/opt/node@22/bin/gmake"
      - "/opt/homebrew/opt/ruby/bin/gmake"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/gmake"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/gmake"
      - "/opt/homebrew/bin/gmake"
      - "/opt/homebrew/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/System/Cryptexes/App/usr/bin/gmake"
      - "/usr/bin/gmake"
      - "/bin/gmake"
      - "/usr/sbin/gmake"
      - "/sbin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/gmake"
      - "/opt/pmk/env/global/bin/gmake"
      - "/Library/Apple/usr/bin/gmake"
      - "/Applications/VMware Fusion.app/Contents/Public/gmake"
      - "/usr/local/share/dotnet/gmake"
      - "/Users/work/.dotnet/tools/gmake"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/gmake"
      - "/Users/work/.cargo/bin/gmake"
      - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts/gmake"
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/make"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/make"
      - "/Users/work/.local/bin/make"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/make"
      - "/opt/homebrew/opt/node@22/bin/make"
      - "/opt/homebrew/opt/ruby/bin/make"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/make"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/make"
      - "/opt/homebrew/bin/make"
      - "/opt/homebrew/sbin/make"
      - "/usr/local/bin/make"
      - "/System/Cryptexes/App/usr/bin/make"
    found: "/usr/bin/make"
    search_context:
      ENV{PATH}:
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/.cargo/bin"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompiler.cmake:73 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:64 (_cmake_find_compiler)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_C_COMPILER"
    description: "C compiler"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cc"
      - "gcc"
      - "cl"
      - "bcc"
      - "xlc"
      - "icx"
      - "clang"
    candidate_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/"
      - "/Users/work/.local/bin/"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/"
      - "/opt/homebrew/opt/node@22/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/work/.dotnet/tools/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/work/.cargo/bin/"
      - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts/"
    searched_directories:
      - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin/cc"
      - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin/cc"
      - "/Users/work/.local/bin/cc"
      - "/Users/work/.nvm/versions/node/v24.13.0/bin/cc"
      - "/opt/homebrew/opt/node@22/bin/cc"
      - "/opt/homebrew/opt/ruby/bin/cc"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/cc"
      - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/cc"
      - "/opt/homebrew/bin/cc"
      - "/opt/homebrew/sbin/cc"
      - "/usr/local/bin/cc"
      - "/System/Cryptexes/App/usr/bin/cc"
    found: "/usr/bin/cc"
    search_context:
      ENV{PATH}:
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/.cargo/bin"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:462 (find_file)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:500 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:122 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCCompilerId.c.in"
    candidate_directories:
      - "/opt/homebrew/share/cmake/Modules/"
    found: "/opt/homebrew/share/cmake/Modules/CMakeCCompilerId.c.in"
    search_context:
      ENV{PATH}:
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/code/ESP-Miner-Gateway/node_modules/.bin"
        - "/Users/work/.cache/node/corepack/v1/pnpm/9.11.0/dist/node-gyp-bin"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/work/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/work/.local/bin"
        - "/Users/work/.nvm/versions/node/v24.13.0/bin"
        - "/opt/homebrew/opt/node@22/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/work/.cargo/bin"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/work/Library/Application Support/JetBrains/Toolbox/scripts"
